# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import superbuilder_middleware_pb2 as superbuilder__middleware__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in superbuilder_middleware_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SuperBuilderStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/SayHello',
                request_serializer=superbuilder__middleware__pb2.SayHelloRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.SayHelloResponse.FromString,
                _registered_method=True)
        self.SayHelloPyllm = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/SayHelloPyllm',
                request_serializer=superbuilder__middleware__pb2.SayHelloRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.SayHelloResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_stream(
                '/SuperBuilder.SuperBuilder/Chat',
                request_serializer=superbuilder__middleware__pb2.ChatRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.StopChat = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/StopChat',
                request_serializer=superbuilder__middleware__pb2.StopChatRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.StopChatResponse.FromString,
                _registered_method=True)
        self.LoadModels = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/LoadModels',
                request_serializer=superbuilder__middleware__pb2.LoadModelsRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.LoadModelsResponse.FromString,
                _registered_method=True)
        self.CheckHealth = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/CheckHealth',
                request_serializer=superbuilder__middleware__pb2.CheckHealthRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.CheckHealthResponse.FromString,
                _registered_method=True)
        self.AddFeedback = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/AddFeedback',
                request_serializer=superbuilder__middleware__pb2.AddFeedbackRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.AddFeedbackResponse.FromString,
                _registered_method=True)
        self.AddFiles = channel.unary_stream(
                '/SuperBuilder.SuperBuilder/AddFiles',
                request_serializer=superbuilder__middleware__pb2.AddFilesRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.AddFilesResponse.FromString,
                _registered_method=True)
        self.StopAddFiles = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/StopAddFiles',
                request_serializer=superbuilder__middleware__pb2.StopAddFilesRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.StopAddFilesResponse.FromString,
                _registered_method=True)
        self.RemoveFiles = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/RemoveFiles',
                request_serializer=superbuilder__middleware__pb2.RemoveFilesRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.RemoveFilesResponse.FromString,
                _registered_method=True)
        self.DownloadFiles = channel.unary_stream(
                '/SuperBuilder.SuperBuilder/DownloadFiles',
                request_serializer=superbuilder__middleware__pb2.DownloadFilesRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.DownloadFilesResponse.FromString,
                _registered_method=True)
        self.GetFileList = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/GetFileList',
                request_serializer=superbuilder__middleware__pb2.GetFileListRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.GetFileListResponse.FromString,
                _registered_method=True)
        self.SetModels = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/SetModels',
                request_serializer=superbuilder__middleware__pb2.SetModelsRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.SetModelsResponse.FromString,
                _registered_method=True)
        self.UnloadModels = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/UnloadModels',
                request_serializer=superbuilder__middleware__pb2.UnloadModelsRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.UnloadModelsResponse.FromString,
                _registered_method=True)
        self.SetParameters = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/SetParameters',
                request_serializer=superbuilder__middleware__pb2.SetParametersRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.SetParametersResponse.FromString,
                _registered_method=True)
        self.ClientDisconnected = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/ClientDisconnected',
                request_serializer=superbuilder__middleware__pb2.ClientDisconnectedRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.ClientDisconnectedResponse.FromString,
                _registered_method=True)
        self.GetClientConfig = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/GetClientConfig',
                request_serializer=superbuilder__middleware__pb2.GetClientConfigRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.GetClientConfigResponse.FromString,
                _registered_method=True)
        self.GetChatHistory = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/GetChatHistory',
                request_serializer=superbuilder__middleware__pb2.GetChatHistoryRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.GetChatHistoryResponse.FromString,
                _registered_method=True)
        self.GetSoftwareUpdate = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/GetSoftwareUpdate',
                request_serializer=superbuilder__middleware__pb2.SayHelloRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.SayHelloResponse.FromString,
                _registered_method=True)
        self.SetVectorDB = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/SetVectorDB',
                request_serializer=superbuilder__middleware__pb2.SetVectorDBRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.SetVectorDBResponse.FromString,
                _registered_method=True)
        self.RemoveSession = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/RemoveSession',
                request_serializer=superbuilder__middleware__pb2.RemoveSessionRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.RemoveSessionResponse.FromString,
                _registered_method=True)
        self.SetSessionName = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/SetSessionName',
                request_serializer=superbuilder__middleware__pb2.SetSessionNameRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.SetSessionNameResponse.FromString,
                _registered_method=True)
        self.SetActiveAssistant = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/SetActiveAssistant',
                request_serializer=superbuilder__middleware__pb2.SetActiveAssistantRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.SetActiveAssistantResponse.FromString,
                _registered_method=True)
        self.SetAssistantViewModel = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/SetAssistantViewModel',
                request_serializer=superbuilder__middleware__pb2.SetAssistantViewModelRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.SetAssistantViewModelResponse.FromString,
                _registered_method=True)
        self.SetUserConfigViewModel = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/SetUserConfigViewModel',
                request_serializer=superbuilder__middleware__pb2.SetUserConfigViewModelRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.SetUserConfigViewModelResponse.FromString,
                _registered_method=True)
        self.ConvertModel = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/ConvertModel',
                request_serializer=superbuilder__middleware__pb2.ConvertModelRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.ConvertModelResponse.FromString,
                _registered_method=True)
        self.UploadModel = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/UploadModel',
                request_serializer=superbuilder__middleware__pb2.UploadModelRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.UploadModelResponse.FromString,
                _registered_method=True)
        self.ExportUserConfig = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/ExportUserConfig',
                request_serializer=superbuilder__middleware__pb2.ExportUserConfigRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.ExportUserConfigResponse.FromString,
                _registered_method=True)
        self.ImportUserConfig = channel.unary_unary(
                '/SuperBuilder.SuperBuilder/ImportUserConfig',
                request_serializer=superbuilder__middleware__pb2.ImportUserConfigRequest.SerializeToString,
                response_deserializer=superbuilder__middleware__pb2.ImportUserConfigResponse.FromString,
                _registered_method=True)


class SuperBuilderServicer(object):
    """The greeting service definition.
    """

    def SayHello(self, request, context):
        """Send a greeting ( For connection testing )
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHelloPyllm(self, request, context):
        """Send a greeting ( For connection testing )
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Send a chat message and stream returns a response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopChat(self, request, context):
        """Sends signal to safely stop the current chat request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModels(self, request, context):
        """Loads the models and any other backend components before chatting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckHealth(self, request, context):
        """Check on health status backend system / service (for example: RAG check)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFeedback(self, request, context):
        """Give LLM feedback on a question's response to improve future responses
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFiles(self, request, context):
        """Upload a list of files to the RAG module to be vector stored, stream the upload progress
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopAddFiles(self, request, context):
        """Sends signal to stop the current upload file request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFiles(self, request, context):
        """Remove a list of files from RAG doc store
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFiles(self, request, context):
        """Request to download a certain list of models, or just all required models if not specified
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileList(self, request, context):
        """Request list of all files uploaded to the loaded document store
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetModels(self, request, context):
        """Set and load models in the backend given a model path
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModels(self, request, context):
        """Unloads models that are in the backend
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetParameters(self, request, context):
        """Change the RAG, LLM, and backend parameters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientDisconnected(self, request, context):
        """Inform the server that the client has disconnected
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClientConfig(self, request, context):
        """Get config info from middleware
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatHistory(self, request, context):
        """Get chat history messages from middleware
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSoftwareUpdate(self, request, context):
        """Send a greeting ( For connection testing )
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVectorDB(self, request, context):
        """Setting Vector DB of default assistant in sqlite db.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveSession(self, request, context):
        """Removes a session and all data related to session from database given session id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSessionName(self, request, context):
        """Update a session name given a valid unique session id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetActiveAssistant(self, request, context):
        """Set Active Assistant or Models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAssistantViewModel(self, request, context):
        """Using an AssistantViewModel it will set the sqlite database active assistant to those fields.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetUserConfigViewModel(self, request, context):
        """Using UserConfigViewModel, sets sqlite database userconfig jsonappsettings to the corresponding fields.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportUserConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportUserConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuperBuilderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=superbuilder__middleware__pb2.SayHelloRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.SayHelloResponse.SerializeToString,
            ),
            'SayHelloPyllm': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHelloPyllm,
                    request_deserializer=superbuilder__middleware__pb2.SayHelloRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.SayHelloResponse.SerializeToString,
            ),
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=superbuilder__middleware__pb2.ChatRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.ChatResponse.SerializeToString,
            ),
            'StopChat': grpc.unary_unary_rpc_method_handler(
                    servicer.StopChat,
                    request_deserializer=superbuilder__middleware__pb2.StopChatRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.StopChatResponse.SerializeToString,
            ),
            'LoadModels': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModels,
                    request_deserializer=superbuilder__middleware__pb2.LoadModelsRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.LoadModelsResponse.SerializeToString,
            ),
            'CheckHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckHealth,
                    request_deserializer=superbuilder__middleware__pb2.CheckHealthRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.CheckHealthResponse.SerializeToString,
            ),
            'AddFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFeedback,
                    request_deserializer=superbuilder__middleware__pb2.AddFeedbackRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.AddFeedbackResponse.SerializeToString,
            ),
            'AddFiles': grpc.unary_stream_rpc_method_handler(
                    servicer.AddFiles,
                    request_deserializer=superbuilder__middleware__pb2.AddFilesRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.AddFilesResponse.SerializeToString,
            ),
            'StopAddFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.StopAddFiles,
                    request_deserializer=superbuilder__middleware__pb2.StopAddFilesRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.StopAddFilesResponse.SerializeToString,
            ),
            'RemoveFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFiles,
                    request_deserializer=superbuilder__middleware__pb2.RemoveFilesRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.RemoveFilesResponse.SerializeToString,
            ),
            'DownloadFiles': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFiles,
                    request_deserializer=superbuilder__middleware__pb2.DownloadFilesRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.DownloadFilesResponse.SerializeToString,
            ),
            'GetFileList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileList,
                    request_deserializer=superbuilder__middleware__pb2.GetFileListRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.GetFileListResponse.SerializeToString,
            ),
            'SetModels': grpc.unary_unary_rpc_method_handler(
                    servicer.SetModels,
                    request_deserializer=superbuilder__middleware__pb2.SetModelsRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.SetModelsResponse.SerializeToString,
            ),
            'UnloadModels': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModels,
                    request_deserializer=superbuilder__middleware__pb2.UnloadModelsRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.UnloadModelsResponse.SerializeToString,
            ),
            'SetParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.SetParameters,
                    request_deserializer=superbuilder__middleware__pb2.SetParametersRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.SetParametersResponse.SerializeToString,
            ),
            'ClientDisconnected': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientDisconnected,
                    request_deserializer=superbuilder__middleware__pb2.ClientDisconnectedRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.ClientDisconnectedResponse.SerializeToString,
            ),
            'GetClientConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClientConfig,
                    request_deserializer=superbuilder__middleware__pb2.GetClientConfigRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.GetClientConfigResponse.SerializeToString,
            ),
            'GetChatHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatHistory,
                    request_deserializer=superbuilder__middleware__pb2.GetChatHistoryRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.GetChatHistoryResponse.SerializeToString,
            ),
            'GetSoftwareUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSoftwareUpdate,
                    request_deserializer=superbuilder__middleware__pb2.SayHelloRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.SayHelloResponse.SerializeToString,
            ),
            'SetVectorDB': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVectorDB,
                    request_deserializer=superbuilder__middleware__pb2.SetVectorDBRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.SetVectorDBResponse.SerializeToString,
            ),
            'RemoveSession': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveSession,
                    request_deserializer=superbuilder__middleware__pb2.RemoveSessionRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.RemoveSessionResponse.SerializeToString,
            ),
            'SetSessionName': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSessionName,
                    request_deserializer=superbuilder__middleware__pb2.SetSessionNameRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.SetSessionNameResponse.SerializeToString,
            ),
            'SetActiveAssistant': grpc.unary_unary_rpc_method_handler(
                    servicer.SetActiveAssistant,
                    request_deserializer=superbuilder__middleware__pb2.SetActiveAssistantRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.SetActiveAssistantResponse.SerializeToString,
            ),
            'SetAssistantViewModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAssistantViewModel,
                    request_deserializer=superbuilder__middleware__pb2.SetAssistantViewModelRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.SetAssistantViewModelResponse.SerializeToString,
            ),
            'SetUserConfigViewModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SetUserConfigViewModel,
                    request_deserializer=superbuilder__middleware__pb2.SetUserConfigViewModelRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.SetUserConfigViewModelResponse.SerializeToString,
            ),
            'ConvertModel': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertModel,
                    request_deserializer=superbuilder__middleware__pb2.ConvertModelRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.ConvertModelResponse.SerializeToString,
            ),
            'UploadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadModel,
                    request_deserializer=superbuilder__middleware__pb2.UploadModelRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.UploadModelResponse.SerializeToString,
            ),
            'ExportUserConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportUserConfig,
                    request_deserializer=superbuilder__middleware__pb2.ExportUserConfigRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.ExportUserConfigResponse.SerializeToString,
            ),
            'ImportUserConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportUserConfig,
                    request_deserializer=superbuilder__middleware__pb2.ImportUserConfigRequest.FromString,
                    response_serializer=superbuilder__middleware__pb2.ImportUserConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SuperBuilder.SuperBuilder', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SuperBuilder.SuperBuilder', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SuperBuilder(object):
    """The greeting service definition.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/SayHello',
            superbuilder__middleware__pb2.SayHelloRequest.SerializeToString,
            superbuilder__middleware__pb2.SayHelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SayHelloPyllm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/SayHelloPyllm',
            superbuilder__middleware__pb2.SayHelloRequest.SerializeToString,
            superbuilder__middleware__pb2.SayHelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/SuperBuilder.SuperBuilder/Chat',
            superbuilder__middleware__pb2.ChatRequest.SerializeToString,
            superbuilder__middleware__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/StopChat',
            superbuilder__middleware__pb2.StopChatRequest.SerializeToString,
            superbuilder__middleware__pb2.StopChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/LoadModels',
            superbuilder__middleware__pb2.LoadModelsRequest.SerializeToString,
            superbuilder__middleware__pb2.LoadModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/CheckHealth',
            superbuilder__middleware__pb2.CheckHealthRequest.SerializeToString,
            superbuilder__middleware__pb2.CheckHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/AddFeedback',
            superbuilder__middleware__pb2.AddFeedbackRequest.SerializeToString,
            superbuilder__middleware__pb2.AddFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/SuperBuilder.SuperBuilder/AddFiles',
            superbuilder__middleware__pb2.AddFilesRequest.SerializeToString,
            superbuilder__middleware__pb2.AddFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopAddFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/StopAddFiles',
            superbuilder__middleware__pb2.StopAddFilesRequest.SerializeToString,
            superbuilder__middleware__pb2.StopAddFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/RemoveFiles',
            superbuilder__middleware__pb2.RemoveFilesRequest.SerializeToString,
            superbuilder__middleware__pb2.RemoveFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/SuperBuilder.SuperBuilder/DownloadFiles',
            superbuilder__middleware__pb2.DownloadFilesRequest.SerializeToString,
            superbuilder__middleware__pb2.DownloadFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFileList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/GetFileList',
            superbuilder__middleware__pb2.GetFileListRequest.SerializeToString,
            superbuilder__middleware__pb2.GetFileListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/SetModels',
            superbuilder__middleware__pb2.SetModelsRequest.SerializeToString,
            superbuilder__middleware__pb2.SetModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/UnloadModels',
            superbuilder__middleware__pb2.UnloadModelsRequest.SerializeToString,
            superbuilder__middleware__pb2.UnloadModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/SetParameters',
            superbuilder__middleware__pb2.SetParametersRequest.SerializeToString,
            superbuilder__middleware__pb2.SetParametersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClientDisconnected(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/ClientDisconnected',
            superbuilder__middleware__pb2.ClientDisconnectedRequest.SerializeToString,
            superbuilder__middleware__pb2.ClientDisconnectedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClientConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/GetClientConfig',
            superbuilder__middleware__pb2.GetClientConfigRequest.SerializeToString,
            superbuilder__middleware__pb2.GetClientConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChatHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/GetChatHistory',
            superbuilder__middleware__pb2.GetChatHistoryRequest.SerializeToString,
            superbuilder__middleware__pb2.GetChatHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSoftwareUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/GetSoftwareUpdate',
            superbuilder__middleware__pb2.SayHelloRequest.SerializeToString,
            superbuilder__middleware__pb2.SayHelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVectorDB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/SetVectorDB',
            superbuilder__middleware__pb2.SetVectorDBRequest.SerializeToString,
            superbuilder__middleware__pb2.SetVectorDBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/RemoveSession',
            superbuilder__middleware__pb2.RemoveSessionRequest.SerializeToString,
            superbuilder__middleware__pb2.RemoveSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSessionName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/SetSessionName',
            superbuilder__middleware__pb2.SetSessionNameRequest.SerializeToString,
            superbuilder__middleware__pb2.SetSessionNameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetActiveAssistant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/SetActiveAssistant',
            superbuilder__middleware__pb2.SetActiveAssistantRequest.SerializeToString,
            superbuilder__middleware__pb2.SetActiveAssistantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAssistantViewModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/SetAssistantViewModel',
            superbuilder__middleware__pb2.SetAssistantViewModelRequest.SerializeToString,
            superbuilder__middleware__pb2.SetAssistantViewModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetUserConfigViewModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/SetUserConfigViewModel',
            superbuilder__middleware__pb2.SetUserConfigViewModelRequest.SerializeToString,
            superbuilder__middleware__pb2.SetUserConfigViewModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConvertModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/ConvertModel',
            superbuilder__middleware__pb2.ConvertModelRequest.SerializeToString,
            superbuilder__middleware__pb2.ConvertModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/UploadModel',
            superbuilder__middleware__pb2.UploadModelRequest.SerializeToString,
            superbuilder__middleware__pb2.UploadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportUserConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/ExportUserConfig',
            superbuilder__middleware__pb2.ExportUserConfigRequest.SerializeToString,
            superbuilder__middleware__pb2.ExportUserConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportUserConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SuperBuilder.SuperBuilder/ImportUserConfig',
            superbuilder__middleware__pb2.ImportUserConfigRequest.SerializeToString,
            superbuilder__middleware__pb2.ImportUserConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
