// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.2
// source: superbuilder_middleware.proto

package SuperBuilderWinService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type SayHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings.
type SayHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{1}
}

func (x *SayHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The request message for the chat.
type ConversationHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationHistory) Reset() {
	*x = ConversationHistory{}
	mi := &file_superbuilder_middleware_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationHistory) ProtoMessage() {}

func (x *ConversationHistory) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationHistory.ProtoReflect.Descriptor instead.
func (*ConversationHistory) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{2}
}

func (x *ConversationHistory) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ConversationHistory) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// The request message for the chat.
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	History       []*ConversationHistory `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	SessionId     int32                  `protobuf:"varint,4,opt,name=sessionId,proto3" json:"sessionId,omitempty"`              // chat session that this chat belongs to
	QueryType     *string                `protobuf:"bytes,5,opt,name=queryType,proto3,oneof" json:"queryType,omitempty"`         // The type of query to do on the attached files
	AttachedFiles *string                `protobuf:"bytes,6,opt,name=attachedFiles,proto3,oneof" json:"attachedFiles,omitempty"` // The files to use specifically for this chat request
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{3}
}

func (x *ChatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ChatRequest) GetHistory() []*ConversationHistory {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *ChatRequest) GetSessionId() int32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *ChatRequest) GetQueryType() string {
	if x != nil && x.QueryType != nil {
		return *x.QueryType
	}
	return ""
}

func (x *ChatRequest) GetAttachedFiles() string {
	if x != nil && x.AttachedFiles != nil {
		return *x.AttachedFiles
	}
	return ""
}

// The response message for the chat.
type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{4}
}

func (x *ChatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopChatRequest) Reset() {
	*x = StopChatRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopChatRequest) ProtoMessage() {}

func (x *StopChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopChatRequest.ProtoReflect.Descriptor instead.
func (*StopChatRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{5}
}

type StopChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopChatResponse) Reset() {
	*x = StopChatResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopChatResponse) ProtoMessage() {}

func (x *StopChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopChatResponse.ProtoReflect.Descriptor instead.
func (*StopChatResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{6}
}

type LoadModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelsRequest) Reset() {
	*x = LoadModelsRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelsRequest) ProtoMessage() {}

func (x *LoadModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelsRequest.ProtoReflect.Descriptor instead.
func (*LoadModelsRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{7}
}

type LoadModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // returns true if successful load
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelsResponse) Reset() {
	*x = LoadModelsResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelsResponse) ProtoMessage() {}

func (x *LoadModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelsResponse.ProtoReflect.Descriptor instead.
func (*LoadModelsResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{8}
}

func (x *LoadModelsResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// The request message containing a placeholder in case we need to send data
type CheckHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeOfCheck   string                 `protobuf:"bytes,1,opt,name=typeOfCheck,proto3" json:"typeOfCheck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthRequest) Reset() {
	*x = CheckHealthRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthRequest) ProtoMessage() {}

func (x *CheckHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthRequest.ProtoReflect.Descriptor instead.
func (*CheckHealthRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{9}
}

func (x *CheckHealthRequest) GetTypeOfCheck() string {
	if x != nil {
		return x.TypeOfCheck
	}
	return ""
}

// The response message containing the status of the system
type CheckHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthResponse) Reset() {
	*x = CheckHealthResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthResponse) ProtoMessage() {}

func (x *CheckHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthResponse.ProtoReflect.Descriptor instead.
func (*CheckHealthResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{10}
}

func (x *CheckHealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// The request message containing a question, its feedback, and type of feedback
type AddFeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Feedback      string                 `protobuf:"bytes,2,opt,name=feedback,proto3" json:"feedback,omitempty"`
	FeedbackType  string                 `protobuf:"bytes,3,opt,name=feedbackType,proto3" json:"feedbackType,omitempty"`
	Answer        *string                `protobuf:"bytes,4,opt,name=answer,proto3,oneof" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFeedbackRequest) Reset() {
	*x = AddFeedbackRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFeedbackRequest) ProtoMessage() {}

func (x *AddFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFeedbackRequest.ProtoReflect.Descriptor instead.
func (*AddFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{11}
}

func (x *AddFeedbackRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *AddFeedbackRequest) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *AddFeedbackRequest) GetFeedbackType() string {
	if x != nil {
		return x.FeedbackType
	}
	return ""
}

func (x *AddFeedbackRequest) GetAnswer() string {
	if x != nil && x.Answer != nil {
		return *x.Answer
	}
	return ""
}

// The response message containing the feedback + question + feedback type
type AddFeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFeedbackResponse) Reset() {
	*x = AddFeedbackResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFeedbackResponse) ProtoMessage() {}

func (x *AddFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFeedbackResponse.ProtoReflect.Descriptor instead.
func (*AddFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{12}
}

func (x *AddFeedbackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The request message containing a list of files to be uploaded to RAG
type AddFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilesToUpload string                 `protobuf:"bytes,1,opt,name=filesToUpload,proto3" json:"filesToUpload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFilesRequest) Reset() {
	*x = AddFilesRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFilesRequest) ProtoMessage() {}

func (x *AddFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFilesRequest.ProtoReflect.Descriptor instead.
func (*AddFilesRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{13}
}

func (x *AddFilesRequest) GetFilesToUpload() string {
	if x != nil {
		return x.FilesToUpload
	}
	return ""
}

// The response message streamed back as a file is uploaded
type AddFilesResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	FilesUploaded        string                 `protobuf:"bytes,1,opt,name=filesUploaded,proto3" json:"filesUploaded,omitempty"`                     // list of files able to be uploaded to vector db
	CurrentFileUploading *string                `protobuf:"bytes,2,opt,name=currentFileUploading,proto3,oneof" json:"currentFileUploading,omitempty"` // current file being uploaded if any
	CurrentFileProgress  *string                `protobuf:"bytes,3,opt,name=currentFileProgress,proto3,oneof" json:"currentFileProgress,omitempty"`   // upload progress percentage from 0 to 100
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AddFilesResponse) Reset() {
	*x = AddFilesResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFilesResponse) ProtoMessage() {}

func (x *AddFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFilesResponse.ProtoReflect.Descriptor instead.
func (*AddFilesResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{14}
}

func (x *AddFilesResponse) GetFilesUploaded() string {
	if x != nil {
		return x.FilesUploaded
	}
	return ""
}

func (x *AddFilesResponse) GetCurrentFileUploading() string {
	if x != nil && x.CurrentFileUploading != nil {
		return *x.CurrentFileUploading
	}
	return ""
}

func (x *AddFilesResponse) GetCurrentFileProgress() string {
	if x != nil && x.CurrentFileProgress != nil {
		return *x.CurrentFileProgress
	}
	return ""
}

// The request message which currently contains nothing (but might be needed in the future)
type GetFileListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileType      string                 `protobuf:"bytes,1,opt,name=fileType,proto3" json:"fileType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileListRequest) Reset() {
	*x = GetFileListRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileListRequest) ProtoMessage() {}

func (x *GetFileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileListRequest.ProtoReflect.Descriptor instead.
func (*GetFileListRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{15}
}

func (x *GetFileListRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

type StopAddFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopAddFilesRequest) Reset() {
	*x = StopAddFilesRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopAddFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAddFilesRequest) ProtoMessage() {}

func (x *StopAddFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAddFilesRequest.ProtoReflect.Descriptor instead.
func (*StopAddFilesRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{16}
}

type StopAddFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopAddFilesResponse) Reset() {
	*x = StopAddFilesResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopAddFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAddFilesResponse) ProtoMessage() {}

func (x *StopAddFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAddFilesResponse.ProtoReflect.Descriptor instead.
func (*StopAddFilesResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{17}
}

// The request message when a client disconnects
type ClientDisconnectedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDisconnectedRequest) Reset() {
	*x = ClientDisconnectedRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDisconnectedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDisconnectedRequest) ProtoMessage() {}

func (x *ClientDisconnectedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDisconnectedRequest.ProtoReflect.Descriptor instead.
func (*ClientDisconnectedRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{18}
}

// The response message containing list of all files found in document store
type GetFileListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileList      string                 `protobuf:"bytes,1,opt,name=fileList,proto3" json:"fileList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileListResponse) Reset() {
	*x = GetFileListResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileListResponse) ProtoMessage() {}

func (x *GetFileListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileListResponse.ProtoReflect.Descriptor instead.
func (*GetFileListResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{19}
}

func (x *GetFileListResponse) GetFileList() string {
	if x != nil {
		return x.FileList
	}
	return ""
}

// The request message containing a list of files to be removed from RAG
type RemoveFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilesToRemove string                 `protobuf:"bytes,1,opt,name=filesToRemove,proto3" json:"filesToRemove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFilesRequest) Reset() {
	*x = RemoveFilesRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFilesRequest) ProtoMessage() {}

func (x *RemoveFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFilesRequest.ProtoReflect.Descriptor instead.
func (*RemoveFilesRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveFilesRequest) GetFilesToRemove() string {
	if x != nil {
		return x.FilesToRemove
	}
	return ""
}

// The response message containing list of all files successfully removed from RAG
type RemoveFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilesRemoved  string                 `protobuf:"bytes,1,opt,name=filesRemoved,proto3" json:"filesRemoved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFilesResponse) Reset() {
	*x = RemoveFilesResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFilesResponse) ProtoMessage() {}

func (x *RemoveFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFilesResponse.ProtoReflect.Descriptor instead.
func (*RemoveFilesResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{21}
}

func (x *RemoveFilesResponse) GetFilesRemoved() string {
	if x != nil {
		return x.FilesRemoved
	}
	return ""
}

// The request message containing list of models to download (if none, download missing)
type DownloadFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUrl       string                 `protobuf:"bytes,1,opt,name=FileUrl,proto3" json:"FileUrl,omitempty"`
	LocalPath     string                 `protobuf:"bytes,2,opt,name=localPath,proto3" json:"localPath,omitempty"`
	TokenId       *string                `protobuf:"bytes,3,opt,name=tokenId,proto3,oneof" json:"tokenId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFilesRequest) Reset() {
	*x = DownloadFilesRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFilesRequest) ProtoMessage() {}

func (x *DownloadFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFilesRequest.ProtoReflect.Descriptor instead.
func (*DownloadFilesRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{22}
}

func (x *DownloadFilesRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *DownloadFilesRequest) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *DownloadFilesRequest) GetTokenId() string {
	if x != nil && x.TokenId != nil {
		return *x.TokenId
	}
	return ""
}

// The response message containing a list of models actually downloaded
type DownloadFilesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Progress       int32                  `protobuf:"varint,1,opt,name=progress,proto3" json:"progress,omitempty"`
	FileDownloaded string                 `protobuf:"bytes,2,opt,name=FileDownloaded,proto3" json:"FileDownloaded,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DownloadFilesResponse) Reset() {
	*x = DownloadFilesResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFilesResponse) ProtoMessage() {}

func (x *DownloadFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFilesResponse.ProtoReflect.Descriptor instead.
func (*DownloadFilesResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{23}
}

func (x *DownloadFilesResponse) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *DownloadFilesResponse) GetFileDownloaded() string {
	if x != nil {
		return x.FileDownloaded
	}
	return ""
}

// The request message which tells the backend which models to set
type SetModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Llm           *string                `protobuf:"bytes,1,opt,name=llm,proto3,oneof" json:"llm,omitempty"`
	Embedder      *string                `protobuf:"bytes,2,opt,name=embedder,proto3,oneof" json:"embedder,omitempty"`
	Ranker        *string                `protobuf:"bytes,3,opt,name=ranker,proto3,oneof" json:"ranker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetModelsRequest) Reset() {
	*x = SetModelsRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModelsRequest) ProtoMessage() {}

func (x *SetModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModelsRequest.ProtoReflect.Descriptor instead.
func (*SetModelsRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{24}
}

func (x *SetModelsRequest) GetLlm() string {
	if x != nil && x.Llm != nil {
		return *x.Llm
	}
	return ""
}

func (x *SetModelsRequest) GetEmbedder() string {
	if x != nil && x.Embedder != nil {
		return *x.Embedder
	}
	return ""
}

func (x *SetModelsRequest) GetRanker() string {
	if x != nil && x.Ranker != nil {
		return *x.Ranker
	}
	return ""
}

// The response message of the models that were set
type SetModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelsLoaded  string                 `protobuf:"bytes,1,opt,name=modelsLoaded,proto3" json:"modelsLoaded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetModelsResponse) Reset() {
	*x = SetModelsResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModelsResponse) ProtoMessage() {}

func (x *SetModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModelsResponse.ProtoReflect.Descriptor instead.
func (*SetModelsResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{25}
}

func (x *SetModelsResponse) GetModelsLoaded() string {
	if x != nil {
		return x.ModelsLoaded
	}
	return ""
}

// The request message which tells the backend which models to unload (true means unload)
type UnloadModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Llm           bool                   `protobuf:"varint,1,opt,name=llm,proto3" json:"llm,omitempty"`
	Embedder      bool                   `protobuf:"varint,2,opt,name=embedder,proto3" json:"embedder,omitempty"`
	Ranker        bool                   `protobuf:"varint,3,opt,name=ranker,proto3" json:"ranker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModelsRequest) Reset() {
	*x = UnloadModelsRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModelsRequest) ProtoMessage() {}

func (x *UnloadModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModelsRequest.ProtoReflect.Descriptor instead.
func (*UnloadModelsRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{26}
}

func (x *UnloadModelsRequest) GetLlm() bool {
	if x != nil {
		return x.Llm
	}
	return false
}

func (x *UnloadModelsRequest) GetEmbedder() bool {
	if x != nil {
		return x.Embedder
	}
	return false
}

func (x *UnloadModelsRequest) GetRanker() bool {
	if x != nil {
		return x.Ranker
	}
	return false
}

// The response message of the models that were unloaded
type UnloadModelsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ModelsUnloaded string                 `protobuf:"bytes,1,opt,name=modelsUnloaded,proto3" json:"modelsUnloaded,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnloadModelsResponse) Reset() {
	*x = UnloadModelsResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModelsResponse) ProtoMessage() {}

func (x *UnloadModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModelsResponse.ProtoReflect.Descriptor instead.
func (*UnloadModelsResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{27}
}

func (x *UnloadModelsResponse) GetModelsUnloaded() string {
	if x != nil {
		return x.ModelsUnloaded
	}
	return ""
}

// A bunch of optional parameters to set, leaving blank is the same as not changing
type SetParametersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ParametersJson string                 `protobuf:"bytes,1,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"` //JSON string of any parameters present in the ModelParametersViewModel classes
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetParametersRequest) Reset() {
	*x = SetParametersRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetParametersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetParametersRequest) ProtoMessage() {}

func (x *SetParametersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetParametersRequest.ProtoReflect.Descriptor instead.
func (*SetParametersRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{28}
}

func (x *SetParametersRequest) GetParametersJson() string {
	if x != nil {
		return x.ParametersJson
	}
	return ""
}

// Response of setting the parameters, nothing for now
type SetParametersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetParametersResponse) Reset() {
	*x = SetParametersResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetParametersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetParametersResponse) ProtoMessage() {}

func (x *SetParametersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetParametersResponse.ProtoReflect.Descriptor instead.
func (*SetParametersResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{29}
}

// The response message when a client disconnects
type ClientDisconnectedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDisconnectedResponse) Reset() {
	*x = ClientDisconnectedResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDisconnectedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDisconnectedResponse) ProtoMessage() {}

func (x *ClientDisconnectedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDisconnectedResponse.ProtoReflect.Descriptor instead.
func (*ClientDisconnectedResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{30}
}

// The request message containing the user's name.
type GetClientConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assistant     string                 `protobuf:"bytes,1,opt,name=assistant,proto3" json:"assistant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientConfigRequest) Reset() {
	*x = GetClientConfigRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientConfigRequest) ProtoMessage() {}

func (x *GetClientConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientConfigRequest.ProtoReflect.Descriptor instead.
func (*GetClientConfigRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{31}
}

func (x *GetClientConfigRequest) GetAssistant() string {
	if x != nil {
		return x.Assistant
	}
	return ""
}

// The response message containing the greetings.
type GetClientConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientConfigResponse) Reset() {
	*x = GetClientConfigResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientConfigResponse) ProtoMessage() {}

func (x *GetClientConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientConfigResponse.ProtoReflect.Descriptor instead.
func (*GetClientConfigResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{32}
}

func (x *GetClientConfigResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// The request message (currently empty)
type GetChatHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryRequest) Reset() {
	*x = GetChatHistoryRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryRequest) ProtoMessage() {}

func (x *GetChatHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetChatHistoryRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{33}
}

// The response message which returns all chat messages
type GetChatHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryResponse) Reset() {
	*x = GetChatHistoryResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryResponse) ProtoMessage() {}

func (x *GetChatHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetChatHistoryResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{34}
}

func (x *GetChatHistoryResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SetVectorDBRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConnectionString string                 `protobuf:"bytes,1,opt,name=connectionString,proto3" json:"connectionString,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetVectorDBRequest) Reset() {
	*x = SetVectorDBRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVectorDBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVectorDBRequest) ProtoMessage() {}

func (x *SetVectorDBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVectorDBRequest.ProtoReflect.Descriptor instead.
func (*SetVectorDBRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{35}
}

func (x *SetVectorDBRequest) GetConnectionString() string {
	if x != nil {
		return x.ConnectionString
	}
	return ""
}

type SetVectorDBResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVectorDBResponse) Reset() {
	*x = SetVectorDBResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVectorDBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVectorDBResponse) ProtoMessage() {}

func (x *SetVectorDBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVectorDBResponse.ProtoReflect.Descriptor instead.
func (*SetVectorDBResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{36}
}

func (x *SetVectorDBResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int32                  `protobuf:"varint,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSessionRequest) Reset() {
	*x = RemoveSessionRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSessionRequest) ProtoMessage() {}

func (x *RemoveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSessionRequest.ProtoReflect.Descriptor instead.
func (*RemoveSessionRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{37}
}

func (x *RemoveSessionRequest) GetSessionId() int32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type RemoveSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSessionResponse) Reset() {
	*x = RemoveSessionResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSessionResponse) ProtoMessage() {}

func (x *RemoveSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSessionResponse.ProtoReflect.Descriptor instead.
func (*RemoveSessionResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{38}
}

func (x *RemoveSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SetSessionNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int32                  `protobuf:"varint,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	SessionName   string                 `protobuf:"bytes,2,opt,name=sessionName,proto3" json:"sessionName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSessionNameRequest) Reset() {
	*x = SetSessionNameRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSessionNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSessionNameRequest) ProtoMessage() {}

func (x *SetSessionNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSessionNameRequest.ProtoReflect.Descriptor instead.
func (*SetSessionNameRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{39}
}

func (x *SetSessionNameRequest) GetSessionId() int32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *SetSessionNameRequest) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

type SetSessionNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSessionNameResponse) Reset() {
	*x = SetSessionNameResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSessionNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSessionNameResponse) ProtoMessage() {}

func (x *SetSessionNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSessionNameResponse.ProtoReflect.Descriptor instead.
func (*SetSessionNameResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{40}
}

func (x *SetSessionNameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SetActiveAssistantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assistant     string                 `protobuf:"bytes,1,opt,name=assistant,proto3" json:"assistant,omitempty"`
	ModelsJson    string                 `protobuf:"bytes,2,opt,name=models_json,json=modelsJson,proto3" json:"models_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetActiveAssistantRequest) Reset() {
	*x = SetActiveAssistantRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetActiveAssistantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActiveAssistantRequest) ProtoMessage() {}

func (x *SetActiveAssistantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActiveAssistantRequest.ProtoReflect.Descriptor instead.
func (*SetActiveAssistantRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{41}
}

func (x *SetActiveAssistantRequest) GetAssistant() string {
	if x != nil {
		return x.Assistant
	}
	return ""
}

func (x *SetActiveAssistantRequest) GetModelsJson() string {
	if x != nil {
		return x.ModelsJson
	}
	return ""
}

type SetActiveAssistantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetActiveAssistantResponse) Reset() {
	*x = SetActiveAssistantResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetActiveAssistantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActiveAssistantResponse) ProtoMessage() {}

func (x *SetActiveAssistantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActiveAssistantResponse.ProtoReflect.Descriptor instead.
func (*SetActiveAssistantResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{42}
}

func (x *SetActiveAssistantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetActiveAssistantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SetAssistantViewModelRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ViewModel       string                 `protobuf:"bytes,1,opt,name=view_model,json=viewModel,proto3" json:"view_model,omitempty"`
	ResetUXSettings bool                   `protobuf:"varint,2,opt,name=resetUXSettings,proto3" json:"resetUXSettings,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetAssistantViewModelRequest) Reset() {
	*x = SetAssistantViewModelRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAssistantViewModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAssistantViewModelRequest) ProtoMessage() {}

func (x *SetAssistantViewModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAssistantViewModelRequest.ProtoReflect.Descriptor instead.
func (*SetAssistantViewModelRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{43}
}

func (x *SetAssistantViewModelRequest) GetViewModel() string {
	if x != nil {
		return x.ViewModel
	}
	return ""
}

func (x *SetAssistantViewModelRequest) GetResetUXSettings() bool {
	if x != nil {
		return x.ResetUXSettings
	}
	return false
}

type SetAssistantViewModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAssistantViewModelResponse) Reset() {
	*x = SetAssistantViewModelResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAssistantViewModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAssistantViewModelResponse) ProtoMessage() {}

func (x *SetAssistantViewModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAssistantViewModelResponse.ProtoReflect.Descriptor instead.
func (*SetAssistantViewModelResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{44}
}

func (x *SetAssistantViewModelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SetUserConfigViewModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewModel     string                 `protobuf:"bytes,1,opt,name=view_model,json=viewModel,proto3" json:"view_model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserConfigViewModelRequest) Reset() {
	*x = SetUserConfigViewModelRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserConfigViewModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserConfigViewModelRequest) ProtoMessage() {}

func (x *SetUserConfigViewModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserConfigViewModelRequest.ProtoReflect.Descriptor instead.
func (*SetUserConfigViewModelRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{45}
}

func (x *SetUserConfigViewModelRequest) GetViewModel() string {
	if x != nil {
		return x.ViewModel
	}
	return ""
}

type SetUserConfigViewModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserConfigViewModelResponse) Reset() {
	*x = SetUserConfigViewModelResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserConfigViewModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserConfigViewModelResponse) ProtoMessage() {}

func (x *SetUserConfigViewModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserConfigViewModelResponse.ProtoReflect.Descriptor instead.
func (*SetUserConfigViewModelResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{46}
}

func (x *SetUserConfigViewModelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConvertModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelPath     string                 `protobuf:"bytes,1,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	Parameters    *string                `protobuf:"bytes,2,opt,name=parameters,proto3,oneof" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertModelRequest) Reset() {
	*x = ConvertModelRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertModelRequest) ProtoMessage() {}

func (x *ConvertModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertModelRequest.ProtoReflect.Descriptor instead.
func (*ConvertModelRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{47}
}

func (x *ConvertModelRequest) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

func (x *ConvertModelRequest) GetParameters() string {
	if x != nil && x.Parameters != nil {
		return *x.Parameters
	}
	return ""
}

type ConvertModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertModelResponse) Reset() {
	*x = ConvertModelResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertModelResponse) ProtoMessage() {}

func (x *ConvertModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertModelResponse.ProtoReflect.Descriptor instead.
func (*ConvertModelResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{48}
}

func (x *ConvertModelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UploadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceDir     string                 `protobuf:"bytes,1,opt,name=source_dir,json=sourceDir,proto3" json:"source_dir,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	ModelType     string                 `protobuf:"bytes,3,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	DownloadLink  string                 `protobuf:"bytes,4,opt,name=download_link,json=downloadLink,proto3" json:"download_link,omitempty"`
	MoveDirectory bool                   `protobuf:"varint,5,opt,name=move_directory,json=moveDirectory,proto3" json:"move_directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadModelRequest) Reset() {
	*x = UploadModelRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[49]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadModelRequest) ProtoMessage() {}

func (x *UploadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[49]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadModelRequest.ProtoReflect.Descriptor instead.
func (*UploadModelRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{49}
}

func (x *UploadModelRequest) GetSourceDir() string {
	if x != nil {
		return x.SourceDir
	}
	return ""
}

func (x *UploadModelRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UploadModelRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *UploadModelRequest) GetDownloadLink() string {
	if x != nil {
		return x.DownloadLink
	}
	return ""
}

func (x *UploadModelRequest) GetMoveDirectory() bool {
	if x != nil {
		return x.MoveDirectory
	}
	return false
}

type UploadModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadModelResponse) Reset() {
	*x = UploadModelResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[50]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadModelResponse) ProtoMessage() {}

func (x *UploadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[50]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadModelResponse.ProtoReflect.Descriptor instead.
func (*UploadModelResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{50}
}

func (x *UploadModelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request message for exporting user configuration
type ExportUserConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantName string                 `protobuf:"bytes,1,opt,name=AssistantName,proto3" json:"AssistantName,omitempty"`
	ExportPath    string                 `protobuf:"bytes,2,opt,name=ExportPath,proto3" json:"ExportPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportUserConfigRequest) Reset() {
	*x = ExportUserConfigRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[51]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportUserConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportUserConfigRequest) ProtoMessage() {}

func (x *ExportUserConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[51]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportUserConfigRequest.ProtoReflect.Descriptor instead.
func (*ExportUserConfigRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{51}
}

func (x *ExportUserConfigRequest) GetAssistantName() string {
	if x != nil {
		return x.AssistantName
	}
	return ""
}

func (x *ExportUserConfigRequest) GetExportPath() string {
	if x != nil {
		return x.ExportPath
	}
	return ""
}

// Response message for exporting user configuration
type ExportUserConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportUserConfigResponse) Reset() {
	*x = ExportUserConfigResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[52]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportUserConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportUserConfigResponse) ProtoMessage() {}

func (x *ExportUserConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[52]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportUserConfigResponse.ProtoReflect.Descriptor instead.
func (*ExportUserConfigResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{52}
}

func (x *ExportUserConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExportUserConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request message for importing user configuration
type ImportUserConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImportPath    string                 `protobuf:"bytes,1,opt,name=ImportPath,proto3" json:"ImportPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportUserConfigRequest) Reset() {
	*x = ImportUserConfigRequest{}
	mi := &file_superbuilder_middleware_proto_msgTypes[53]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportUserConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportUserConfigRequest) ProtoMessage() {}

func (x *ImportUserConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[53]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportUserConfigRequest.ProtoReflect.Descriptor instead.
func (*ImportUserConfigRequest) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{53}
}

func (x *ImportUserConfigRequest) GetImportPath() string {
	if x != nil {
		return x.ImportPath
	}
	return ""
}

// Response message for importing user configuration
type ImportUserConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportUserConfigResponse) Reset() {
	*x = ImportUserConfigResponse{}
	mi := &file_superbuilder_middleware_proto_msgTypes[54]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportUserConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportUserConfigResponse) ProtoMessage() {}

func (x *ImportUserConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superbuilder_middleware_proto_msgTypes[54]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportUserConfigResponse.ProtoReflect.Descriptor instead.
func (*ImportUserConfigResponse) Descriptor() ([]byte, []int) {
	return file_superbuilder_middleware_proto_rawDescGZIP(), []int{54}
}

func (x *ImportUserConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ImportUserConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_superbuilder_middleware_proto protoreflect.FileDescriptor

const file_superbuilder_middleware_proto_rawDesc = "" +
	"\n" +
	"\x1dsuperbuilder_middleware.proto\x12\fSuperBuilder\"%\n" +
	"\x0fSayHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x10SayHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"C\n" +
	"\x13ConversationHistory\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x82\x02\n" +
	"\vChatRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12;\n" +
	"\ahistory\x18\x03 \x03(\v2!.SuperBuilder.ConversationHistoryR\ahistory\x12\x1c\n" +
	"\tsessionId\x18\x04 \x01(\x05R\tsessionId\x12!\n" +
	"\tqueryType\x18\x05 \x01(\tH\x00R\tqueryType\x88\x01\x01\x12)\n" +
	"\rattachedFiles\x18\x06 \x01(\tH\x01R\rattachedFiles\x88\x01\x01B\f\n" +
	"\n" +
	"_queryTypeB\x10\n" +
	"\x0e_attachedFiles\"(\n" +
	"\fChatResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x11\n" +
	"\x0fStopChatRequest\"\x12\n" +
	"\x10StopChatResponse\"\x13\n" +
	"\x11LoadModelsRequest\",\n" +
	"\x12LoadModelsResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"6\n" +
	"\x12CheckHealthRequest\x12 \n" +
	"\vtypeOfCheck\x18\x01 \x01(\tR\vtypeOfCheck\"-\n" +
	"\x13CheckHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x98\x01\n" +
	"\x12AddFeedbackRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x1a\n" +
	"\bfeedback\x18\x02 \x01(\tR\bfeedback\x12\"\n" +
	"\ffeedbackType\x18\x03 \x01(\tR\ffeedbackType\x12\x1b\n" +
	"\x06answer\x18\x04 \x01(\tH\x00R\x06answer\x88\x01\x01B\t\n" +
	"\a_answer\"/\n" +
	"\x13AddFeedbackResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"7\n" +
	"\x0fAddFilesRequest\x12$\n" +
	"\rfilesToUpload\x18\x01 \x01(\tR\rfilesToUpload\"\xd9\x01\n" +
	"\x10AddFilesResponse\x12$\n" +
	"\rfilesUploaded\x18\x01 \x01(\tR\rfilesUploaded\x127\n" +
	"\x14currentFileUploading\x18\x02 \x01(\tH\x00R\x14currentFileUploading\x88\x01\x01\x125\n" +
	"\x13currentFileProgress\x18\x03 \x01(\tH\x01R\x13currentFileProgress\x88\x01\x01B\x17\n" +
	"\x15_currentFileUploadingB\x16\n" +
	"\x14_currentFileProgress\"0\n" +
	"\x12GetFileListRequest\x12\x1a\n" +
	"\bfileType\x18\x01 \x01(\tR\bfileType\"\x15\n" +
	"\x13StopAddFilesRequest\"\x16\n" +
	"\x14StopAddFilesResponse\"\x1b\n" +
	"\x19ClientDisconnectedRequest\"1\n" +
	"\x13GetFileListResponse\x12\x1a\n" +
	"\bfileList\x18\x01 \x01(\tR\bfileList\":\n" +
	"\x12RemoveFilesRequest\x12$\n" +
	"\rfilesToRemove\x18\x01 \x01(\tR\rfilesToRemove\"9\n" +
	"\x13RemoveFilesResponse\x12\"\n" +
	"\ffilesRemoved\x18\x01 \x01(\tR\ffilesRemoved\"y\n" +
	"\x14DownloadFilesRequest\x12\x18\n" +
	"\aFileUrl\x18\x01 \x01(\tR\aFileUrl\x12\x1c\n" +
	"\tlocalPath\x18\x02 \x01(\tR\tlocalPath\x12\x1d\n" +
	"\atokenId\x18\x03 \x01(\tH\x00R\atokenId\x88\x01\x01B\n" +
	"\n" +
	"\b_tokenId\"[\n" +
	"\x15DownloadFilesResponse\x12\x1a\n" +
	"\bprogress\x18\x01 \x01(\x05R\bprogress\x12&\n" +
	"\x0eFileDownloaded\x18\x02 \x01(\tR\x0eFileDownloaded\"\x87\x01\n" +
	"\x10SetModelsRequest\x12\x15\n" +
	"\x03llm\x18\x01 \x01(\tH\x00R\x03llm\x88\x01\x01\x12\x1f\n" +
	"\bembedder\x18\x02 \x01(\tH\x01R\bembedder\x88\x01\x01\x12\x1b\n" +
	"\x06ranker\x18\x03 \x01(\tH\x02R\x06ranker\x88\x01\x01B\x06\n" +
	"\x04_llmB\v\n" +
	"\t_embedderB\t\n" +
	"\a_ranker\"7\n" +
	"\x11SetModelsResponse\x12\"\n" +
	"\fmodelsLoaded\x18\x01 \x01(\tR\fmodelsLoaded\"[\n" +
	"\x13UnloadModelsRequest\x12\x10\n" +
	"\x03llm\x18\x01 \x01(\bR\x03llm\x12\x1a\n" +
	"\bembedder\x18\x02 \x01(\bR\bembedder\x12\x16\n" +
	"\x06ranker\x18\x03 \x01(\bR\x06ranker\">\n" +
	"\x14UnloadModelsResponse\x12&\n" +
	"\x0emodelsUnloaded\x18\x01 \x01(\tR\x0emodelsUnloaded\"?\n" +
	"\x14SetParametersRequest\x12'\n" +
	"\x0fparameters_json\x18\x01 \x01(\tR\x0eparametersJson\"\x17\n" +
	"\x15SetParametersResponse\"\x1c\n" +
	"\x1aClientDisconnectedResponse\"6\n" +
	"\x16GetClientConfigRequest\x12\x1c\n" +
	"\tassistant\x18\x01 \x01(\tR\tassistant\"-\n" +
	"\x17GetClientConfigResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"\x17\n" +
	"\x15GetChatHistoryRequest\",\n" +
	"\x16GetChatHistoryResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"@\n" +
	"\x12SetVectorDBRequest\x12*\n" +
	"\x10connectionString\x18\x01 \x01(\tR\x10connectionString\"/\n" +
	"\x13SetVectorDBResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"4\n" +
	"\x14RemoveSessionRequest\x12\x1c\n" +
	"\tsessionId\x18\x01 \x01(\x05R\tsessionId\"1\n" +
	"\x15RemoveSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"W\n" +
	"\x15SetSessionNameRequest\x12\x1c\n" +
	"\tsessionId\x18\x01 \x01(\x05R\tsessionId\x12 \n" +
	"\vsessionName\x18\x02 \x01(\tR\vsessionName\"2\n" +
	"\x16SetSessionNameResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Z\n" +
	"\x19SetActiveAssistantRequest\x12\x1c\n" +
	"\tassistant\x18\x01 \x01(\tR\tassistant\x12\x1f\n" +
	"\vmodels_json\x18\x02 \x01(\tR\n" +
	"modelsJson\"P\n" +
	"\x1aSetActiveAssistantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"g\n" +
	"\x1cSetAssistantViewModelRequest\x12\x1d\n" +
	"\n" +
	"view_model\x18\x01 \x01(\tR\tviewModel\x12(\n" +
	"\x0fresetUXSettings\x18\x02 \x01(\bR\x0fresetUXSettings\"9\n" +
	"\x1dSetAssistantViewModelResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\">\n" +
	"\x1dSetUserConfigViewModelRequest\x12\x1d\n" +
	"\n" +
	"view_model\x18\x01 \x01(\tR\tviewModel\":\n" +
	"\x1eSetUserConfigViewModelResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"h\n" +
	"\x13ConvertModelRequest\x12\x1d\n" +
	"\n" +
	"model_path\x18\x01 \x01(\tR\tmodelPath\x12#\n" +
	"\n" +
	"parameters\x18\x02 \x01(\tH\x00R\n" +
	"parameters\x88\x01\x01B\r\n" +
	"\v_parameters\"0\n" +
	"\x14ConvertModelResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xb4\x01\n" +
	"\x12UploadModelRequest\x12\x1d\n" +
	"\n" +
	"source_dir\x18\x01 \x01(\tR\tsourceDir\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"model_type\x18\x03 \x01(\tR\tmodelType\x12#\n" +
	"\rdownload_link\x18\x04 \x01(\tR\fdownloadLink\x12%\n" +
	"\x0emove_directory\x18\x05 \x01(\bR\rmoveDirectory\"/\n" +
	"\x13UploadModelResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"_\n" +
	"\x17ExportUserConfigRequest\x12$\n" +
	"\rAssistantName\x18\x01 \x01(\tR\rAssistantName\x12\x1e\n" +
	"\n" +
	"ExportPath\x18\x02 \x01(\tR\n" +
	"ExportPath\"N\n" +
	"\x18ExportUserConfigResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\"9\n" +
	"\x17ImportUserConfigRequest\x12\x1e\n" +
	"\n" +
	"ImportPath\x18\x01 \x01(\tR\n" +
	"ImportPath\"N\n" +
	"\x18ImportUserConfigResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage2\x9b\x14\n" +
	"\fSuperBuilder\x12I\n" +
	"\bSayHello\x12\x1d.SuperBuilder.SayHelloRequest\x1a\x1e.SuperBuilder.SayHelloResponse\x12N\n" +
	"\rSayHelloPyllm\x12\x1d.SuperBuilder.SayHelloRequest\x1a\x1e.SuperBuilder.SayHelloResponse\x12?\n" +
	"\x04Chat\x12\x19.SuperBuilder.ChatRequest\x1a\x1a.SuperBuilder.ChatResponse0\x01\x12I\n" +
	"\bStopChat\x12\x1d.SuperBuilder.StopChatRequest\x1a\x1e.SuperBuilder.StopChatResponse\x12O\n" +
	"\n" +
	"LoadModels\x12\x1f.SuperBuilder.LoadModelsRequest\x1a .SuperBuilder.LoadModelsResponse\x12R\n" +
	"\vCheckHealth\x12 .SuperBuilder.CheckHealthRequest\x1a!.SuperBuilder.CheckHealthResponse\x12R\n" +
	"\vAddFeedback\x12 .SuperBuilder.AddFeedbackRequest\x1a!.SuperBuilder.AddFeedbackResponse\x12K\n" +
	"\bAddFiles\x12\x1d.SuperBuilder.AddFilesRequest\x1a\x1e.SuperBuilder.AddFilesResponse0\x01\x12U\n" +
	"\fStopAddFiles\x12!.SuperBuilder.StopAddFilesRequest\x1a\".SuperBuilder.StopAddFilesResponse\x12R\n" +
	"\vRemoveFiles\x12 .SuperBuilder.RemoveFilesRequest\x1a!.SuperBuilder.RemoveFilesResponse\x12Z\n" +
	"\rDownloadFiles\x12\".SuperBuilder.DownloadFilesRequest\x1a#.SuperBuilder.DownloadFilesResponse0\x01\x12R\n" +
	"\vGetFileList\x12 .SuperBuilder.GetFileListRequest\x1a!.SuperBuilder.GetFileListResponse\x12L\n" +
	"\tSetModels\x12\x1e.SuperBuilder.SetModelsRequest\x1a\x1f.SuperBuilder.SetModelsResponse\x12U\n" +
	"\fUnloadModels\x12!.SuperBuilder.UnloadModelsRequest\x1a\".SuperBuilder.UnloadModelsResponse\x12X\n" +
	"\rSetParameters\x12\".SuperBuilder.SetParametersRequest\x1a#.SuperBuilder.SetParametersResponse\x12g\n" +
	"\x12ClientDisconnected\x12'.SuperBuilder.ClientDisconnectedRequest\x1a(.SuperBuilder.ClientDisconnectedResponse\x12^\n" +
	"\x0fGetClientConfig\x12$.SuperBuilder.GetClientConfigRequest\x1a%.SuperBuilder.GetClientConfigResponse\x12[\n" +
	"\x0eGetChatHistory\x12#.SuperBuilder.GetChatHistoryRequest\x1a$.SuperBuilder.GetChatHistoryResponse\x12R\n" +
	"\x11GetSoftwareUpdate\x12\x1d.SuperBuilder.SayHelloRequest\x1a\x1e.SuperBuilder.SayHelloResponse\x12R\n" +
	"\vSetVectorDB\x12 .SuperBuilder.SetVectorDBRequest\x1a!.SuperBuilder.SetVectorDBResponse\x12X\n" +
	"\rRemoveSession\x12\".SuperBuilder.RemoveSessionRequest\x1a#.SuperBuilder.RemoveSessionResponse\x12[\n" +
	"\x0eSetSessionName\x12#.SuperBuilder.SetSessionNameRequest\x1a$.SuperBuilder.SetSessionNameResponse\x12g\n" +
	"\x12SetActiveAssistant\x12'.SuperBuilder.SetActiveAssistantRequest\x1a(.SuperBuilder.SetActiveAssistantResponse\x12p\n" +
	"\x15SetAssistantViewModel\x12*.SuperBuilder.SetAssistantViewModelRequest\x1a+.SuperBuilder.SetAssistantViewModelResponse\x12s\n" +
	"\x16SetUserConfigViewModel\x12+.SuperBuilder.SetUserConfigViewModelRequest\x1a,.SuperBuilder.SetUserConfigViewModelResponse\x12U\n" +
	"\fConvertModel\x12!.SuperBuilder.ConvertModelRequest\x1a\".SuperBuilder.ConvertModelResponse\x12R\n" +
	"\vUploadModel\x12 .SuperBuilder.UploadModelRequest\x1a!.SuperBuilder.UploadModelResponse\x12a\n" +
	"\x10ExportUserConfig\x12%.SuperBuilder.ExportUserConfigRequest\x1a&.SuperBuilder.ExportUserConfigResponse\x12a\n" +
	"\x10ImportUserConfig\x12%.SuperBuilder.ImportUserConfigRequest\x1a&.SuperBuilder.ImportUserConfigResponseB>Z#superbuilder/SuperBuilderWinService\xaa\x02\x16SuperBuilderWinServiceb\x06proto3"

var (
	file_superbuilder_middleware_proto_rawDescOnce sync.Once
	file_superbuilder_middleware_proto_rawDescData []byte
)

func file_superbuilder_middleware_proto_rawDescGZIP() []byte {
	file_superbuilder_middleware_proto_rawDescOnce.Do(func() {
		file_superbuilder_middleware_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_superbuilder_middleware_proto_rawDesc), len(file_superbuilder_middleware_proto_rawDesc)))
	})
	return file_superbuilder_middleware_proto_rawDescData
}

var file_superbuilder_middleware_proto_msgTypes = make([]protoimpl.MessageInfo, 55)
var file_superbuilder_middleware_proto_goTypes = []any{
	(*SayHelloRequest)(nil),                // 0: SuperBuilder.SayHelloRequest
	(*SayHelloResponse)(nil),               // 1: SuperBuilder.SayHelloResponse
	(*ConversationHistory)(nil),            // 2: SuperBuilder.ConversationHistory
	(*ChatRequest)(nil),                    // 3: SuperBuilder.ChatRequest
	(*ChatResponse)(nil),                   // 4: SuperBuilder.ChatResponse
	(*StopChatRequest)(nil),                // 5: SuperBuilder.StopChatRequest
	(*StopChatResponse)(nil),               // 6: SuperBuilder.StopChatResponse
	(*LoadModelsRequest)(nil),              // 7: SuperBuilder.LoadModelsRequest
	(*LoadModelsResponse)(nil),             // 8: SuperBuilder.LoadModelsResponse
	(*CheckHealthRequest)(nil),             // 9: SuperBuilder.CheckHealthRequest
	(*CheckHealthResponse)(nil),            // 10: SuperBuilder.CheckHealthResponse
	(*AddFeedbackRequest)(nil),             // 11: SuperBuilder.AddFeedbackRequest
	(*AddFeedbackResponse)(nil),            // 12: SuperBuilder.AddFeedbackResponse
	(*AddFilesRequest)(nil),                // 13: SuperBuilder.AddFilesRequest
	(*AddFilesResponse)(nil),               // 14: SuperBuilder.AddFilesResponse
	(*GetFileListRequest)(nil),             // 15: SuperBuilder.GetFileListRequest
	(*StopAddFilesRequest)(nil),            // 16: SuperBuilder.StopAddFilesRequest
	(*StopAddFilesResponse)(nil),           // 17: SuperBuilder.StopAddFilesResponse
	(*ClientDisconnectedRequest)(nil),      // 18: SuperBuilder.ClientDisconnectedRequest
	(*GetFileListResponse)(nil),            // 19: SuperBuilder.GetFileListResponse
	(*RemoveFilesRequest)(nil),             // 20: SuperBuilder.RemoveFilesRequest
	(*RemoveFilesResponse)(nil),            // 21: SuperBuilder.RemoveFilesResponse
	(*DownloadFilesRequest)(nil),           // 22: SuperBuilder.DownloadFilesRequest
	(*DownloadFilesResponse)(nil),          // 23: SuperBuilder.DownloadFilesResponse
	(*SetModelsRequest)(nil),               // 24: SuperBuilder.SetModelsRequest
	(*SetModelsResponse)(nil),              // 25: SuperBuilder.SetModelsResponse
	(*UnloadModelsRequest)(nil),            // 26: SuperBuilder.UnloadModelsRequest
	(*UnloadModelsResponse)(nil),           // 27: SuperBuilder.UnloadModelsResponse
	(*SetParametersRequest)(nil),           // 28: SuperBuilder.SetParametersRequest
	(*SetParametersResponse)(nil),          // 29: SuperBuilder.SetParametersResponse
	(*ClientDisconnectedResponse)(nil),     // 30: SuperBuilder.ClientDisconnectedResponse
	(*GetClientConfigRequest)(nil),         // 31: SuperBuilder.GetClientConfigRequest
	(*GetClientConfigResponse)(nil),        // 32: SuperBuilder.GetClientConfigResponse
	(*GetChatHistoryRequest)(nil),          // 33: SuperBuilder.GetChatHistoryRequest
	(*GetChatHistoryResponse)(nil),         // 34: SuperBuilder.GetChatHistoryResponse
	(*SetVectorDBRequest)(nil),             // 35: SuperBuilder.SetVectorDBRequest
	(*SetVectorDBResponse)(nil),            // 36: SuperBuilder.SetVectorDBResponse
	(*RemoveSessionRequest)(nil),           // 37: SuperBuilder.RemoveSessionRequest
	(*RemoveSessionResponse)(nil),          // 38: SuperBuilder.RemoveSessionResponse
	(*SetSessionNameRequest)(nil),          // 39: SuperBuilder.SetSessionNameRequest
	(*SetSessionNameResponse)(nil),         // 40: SuperBuilder.SetSessionNameResponse
	(*SetActiveAssistantRequest)(nil),      // 41: SuperBuilder.SetActiveAssistantRequest
	(*SetActiveAssistantResponse)(nil),     // 42: SuperBuilder.SetActiveAssistantResponse
	(*SetAssistantViewModelRequest)(nil),   // 43: SuperBuilder.SetAssistantViewModelRequest
	(*SetAssistantViewModelResponse)(nil),  // 44: SuperBuilder.SetAssistantViewModelResponse
	(*SetUserConfigViewModelRequest)(nil),  // 45: SuperBuilder.SetUserConfigViewModelRequest
	(*SetUserConfigViewModelResponse)(nil), // 46: SuperBuilder.SetUserConfigViewModelResponse
	(*ConvertModelRequest)(nil),            // 47: SuperBuilder.ConvertModelRequest
	(*ConvertModelResponse)(nil),           // 48: SuperBuilder.ConvertModelResponse
	(*UploadModelRequest)(nil),             // 49: SuperBuilder.UploadModelRequest
	(*UploadModelResponse)(nil),            // 50: SuperBuilder.UploadModelResponse
	(*ExportUserConfigRequest)(nil),        // 51: SuperBuilder.ExportUserConfigRequest
	(*ExportUserConfigResponse)(nil),       // 52: SuperBuilder.ExportUserConfigResponse
	(*ImportUserConfigRequest)(nil),        // 53: SuperBuilder.ImportUserConfigRequest
	(*ImportUserConfigResponse)(nil),       // 54: SuperBuilder.ImportUserConfigResponse
}
var file_superbuilder_middleware_proto_depIdxs = []int32{
	2,  // 0: SuperBuilder.ChatRequest.history:type_name -> SuperBuilder.ConversationHistory
	0,  // 1: SuperBuilder.SuperBuilder.SayHello:input_type -> SuperBuilder.SayHelloRequest
	0,  // 2: SuperBuilder.SuperBuilder.SayHelloPyllm:input_type -> SuperBuilder.SayHelloRequest
	3,  // 3: SuperBuilder.SuperBuilder.Chat:input_type -> SuperBuilder.ChatRequest
	5,  // 4: SuperBuilder.SuperBuilder.StopChat:input_type -> SuperBuilder.StopChatRequest
	7,  // 5: SuperBuilder.SuperBuilder.LoadModels:input_type -> SuperBuilder.LoadModelsRequest
	9,  // 6: SuperBuilder.SuperBuilder.CheckHealth:input_type -> SuperBuilder.CheckHealthRequest
	11, // 7: SuperBuilder.SuperBuilder.AddFeedback:input_type -> SuperBuilder.AddFeedbackRequest
	13, // 8: SuperBuilder.SuperBuilder.AddFiles:input_type -> SuperBuilder.AddFilesRequest
	16, // 9: SuperBuilder.SuperBuilder.StopAddFiles:input_type -> SuperBuilder.StopAddFilesRequest
	20, // 10: SuperBuilder.SuperBuilder.RemoveFiles:input_type -> SuperBuilder.RemoveFilesRequest
	22, // 11: SuperBuilder.SuperBuilder.DownloadFiles:input_type -> SuperBuilder.DownloadFilesRequest
	15, // 12: SuperBuilder.SuperBuilder.GetFileList:input_type -> SuperBuilder.GetFileListRequest
	24, // 13: SuperBuilder.SuperBuilder.SetModels:input_type -> SuperBuilder.SetModelsRequest
	26, // 14: SuperBuilder.SuperBuilder.UnloadModels:input_type -> SuperBuilder.UnloadModelsRequest
	28, // 15: SuperBuilder.SuperBuilder.SetParameters:input_type -> SuperBuilder.SetParametersRequest
	18, // 16: SuperBuilder.SuperBuilder.ClientDisconnected:input_type -> SuperBuilder.ClientDisconnectedRequest
	31, // 17: SuperBuilder.SuperBuilder.GetClientConfig:input_type -> SuperBuilder.GetClientConfigRequest
	33, // 18: SuperBuilder.SuperBuilder.GetChatHistory:input_type -> SuperBuilder.GetChatHistoryRequest
	0,  // 19: SuperBuilder.SuperBuilder.GetSoftwareUpdate:input_type -> SuperBuilder.SayHelloRequest
	35, // 20: SuperBuilder.SuperBuilder.SetVectorDB:input_type -> SuperBuilder.SetVectorDBRequest
	37, // 21: SuperBuilder.SuperBuilder.RemoveSession:input_type -> SuperBuilder.RemoveSessionRequest
	39, // 22: SuperBuilder.SuperBuilder.SetSessionName:input_type -> SuperBuilder.SetSessionNameRequest
	41, // 23: SuperBuilder.SuperBuilder.SetActiveAssistant:input_type -> SuperBuilder.SetActiveAssistantRequest
	43, // 24: SuperBuilder.SuperBuilder.SetAssistantViewModel:input_type -> SuperBuilder.SetAssistantViewModelRequest
	45, // 25: SuperBuilder.SuperBuilder.SetUserConfigViewModel:input_type -> SuperBuilder.SetUserConfigViewModelRequest
	47, // 26: SuperBuilder.SuperBuilder.ConvertModel:input_type -> SuperBuilder.ConvertModelRequest
	49, // 27: SuperBuilder.SuperBuilder.UploadModel:input_type -> SuperBuilder.UploadModelRequest
	51, // 28: SuperBuilder.SuperBuilder.ExportUserConfig:input_type -> SuperBuilder.ExportUserConfigRequest
	53, // 29: SuperBuilder.SuperBuilder.ImportUserConfig:input_type -> SuperBuilder.ImportUserConfigRequest
	1,  // 30: SuperBuilder.SuperBuilder.SayHello:output_type -> SuperBuilder.SayHelloResponse
	1,  // 31: SuperBuilder.SuperBuilder.SayHelloPyllm:output_type -> SuperBuilder.SayHelloResponse
	4,  // 32: SuperBuilder.SuperBuilder.Chat:output_type -> SuperBuilder.ChatResponse
	6,  // 33: SuperBuilder.SuperBuilder.StopChat:output_type -> SuperBuilder.StopChatResponse
	8,  // 34: SuperBuilder.SuperBuilder.LoadModels:output_type -> SuperBuilder.LoadModelsResponse
	10, // 35: SuperBuilder.SuperBuilder.CheckHealth:output_type -> SuperBuilder.CheckHealthResponse
	12, // 36: SuperBuilder.SuperBuilder.AddFeedback:output_type -> SuperBuilder.AddFeedbackResponse
	14, // 37: SuperBuilder.SuperBuilder.AddFiles:output_type -> SuperBuilder.AddFilesResponse
	17, // 38: SuperBuilder.SuperBuilder.StopAddFiles:output_type -> SuperBuilder.StopAddFilesResponse
	21, // 39: SuperBuilder.SuperBuilder.RemoveFiles:output_type -> SuperBuilder.RemoveFilesResponse
	23, // 40: SuperBuilder.SuperBuilder.DownloadFiles:output_type -> SuperBuilder.DownloadFilesResponse
	19, // 41: SuperBuilder.SuperBuilder.GetFileList:output_type -> SuperBuilder.GetFileListResponse
	25, // 42: SuperBuilder.SuperBuilder.SetModels:output_type -> SuperBuilder.SetModelsResponse
	27, // 43: SuperBuilder.SuperBuilder.UnloadModels:output_type -> SuperBuilder.UnloadModelsResponse
	29, // 44: SuperBuilder.SuperBuilder.SetParameters:output_type -> SuperBuilder.SetParametersResponse
	30, // 45: SuperBuilder.SuperBuilder.ClientDisconnected:output_type -> SuperBuilder.ClientDisconnectedResponse
	32, // 46: SuperBuilder.SuperBuilder.GetClientConfig:output_type -> SuperBuilder.GetClientConfigResponse
	34, // 47: SuperBuilder.SuperBuilder.GetChatHistory:output_type -> SuperBuilder.GetChatHistoryResponse
	1,  // 48: SuperBuilder.SuperBuilder.GetSoftwareUpdate:output_type -> SuperBuilder.SayHelloResponse
	36, // 49: SuperBuilder.SuperBuilder.SetVectorDB:output_type -> SuperBuilder.SetVectorDBResponse
	38, // 50: SuperBuilder.SuperBuilder.RemoveSession:output_type -> SuperBuilder.RemoveSessionResponse
	40, // 51: SuperBuilder.SuperBuilder.SetSessionName:output_type -> SuperBuilder.SetSessionNameResponse
	42, // 52: SuperBuilder.SuperBuilder.SetActiveAssistant:output_type -> SuperBuilder.SetActiveAssistantResponse
	44, // 53: SuperBuilder.SuperBuilder.SetAssistantViewModel:output_type -> SuperBuilder.SetAssistantViewModelResponse
	46, // 54: SuperBuilder.SuperBuilder.SetUserConfigViewModel:output_type -> SuperBuilder.SetUserConfigViewModelResponse
	48, // 55: SuperBuilder.SuperBuilder.ConvertModel:output_type -> SuperBuilder.ConvertModelResponse
	50, // 56: SuperBuilder.SuperBuilder.UploadModel:output_type -> SuperBuilder.UploadModelResponse
	52, // 57: SuperBuilder.SuperBuilder.ExportUserConfig:output_type -> SuperBuilder.ExportUserConfigResponse
	54, // 58: SuperBuilder.SuperBuilder.ImportUserConfig:output_type -> SuperBuilder.ImportUserConfigResponse
	30, // [30:59] is the sub-list for method output_type
	1,  // [1:30] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_superbuilder_middleware_proto_init() }
func file_superbuilder_middleware_proto_init() {
	if File_superbuilder_middleware_proto != nil {
		return
	}
	file_superbuilder_middleware_proto_msgTypes[3].OneofWrappers = []any{}
	file_superbuilder_middleware_proto_msgTypes[11].OneofWrappers = []any{}
	file_superbuilder_middleware_proto_msgTypes[14].OneofWrappers = []any{}
	file_superbuilder_middleware_proto_msgTypes[22].OneofWrappers = []any{}
	file_superbuilder_middleware_proto_msgTypes[24].OneofWrappers = []any{}
	file_superbuilder_middleware_proto_msgTypes[47].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_superbuilder_middleware_proto_rawDesc), len(file_superbuilder_middleware_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   55,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_superbuilder_middleware_proto_goTypes,
		DependencyIndexes: file_superbuilder_middleware_proto_depIdxs,
		MessageInfos:      file_superbuilder_middleware_proto_msgTypes,
	}.Build()
	File_superbuilder_middleware_proto = out.File
	file_superbuilder_middleware_proto_goTypes = nil
	file_superbuilder_middleware_proto_depIdxs = nil
}
